inserted the new go errors lib
ditointernet/go-dito pull request #17
Opened 2021-04-26 20:06 UTC by straubartur

## Answer this before creating the PR
- Who is the responsible for the production test after the merge?

- How to test it?
Yo can run int with `go test`
- Does it have documentation?
No
- Which systems are impacted for?
This lib will provide a errors libs standart
- Is there any PR dependency?
No
## Checklist:
- [ ] I've runned the migration project if necessary
- [ ] I've created the environment variables if necessary
- [ ] I've created the documentation if necessary

2021-04-26 21:18 UTC, RaiTamarindo requested changes

2021-04-26 21:38 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +	DefaultCode CodeType = ""
For sure... I don't have any preference neither knowledge at this point, but using the upper case syntax sound good to me, since it's like a "constant" value.

Do you have any thoughts about that? @RaiTamarindo @straubartur 

PS: Just remenber that the Kind attribute will be translated to the wire context (e.g.: translated to a HTTP status code)

2021-04-26 21:38 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +type KindType string
The `KindType` is a universal concept that should be defined by this package. So, I think we should reason on which Kinds could be exposed by this package. @RaiTamarindo @straubartur any suggestions?

2021-04-26 21:38 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +type KindType string
Another thing that comes to my mind is that, at some point, there must exist some kind of Mapper that translates a `KindType` to an `HTTP Status Code` or a `gRPC Status Code`. How should we do that? What do you think about handling this issue like a methos of `KindType`.

Proposed usage:

```golang
errors.Kind(err).ToHttpStatusCode()
```

2021-04-26 21:38 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +func New(kind KindType, message string, code CodeType) CustomError {
@straubartur I like to reason about the precedence order of params. In my opnion, this approach sounds better:

```golang
func New(message string, kind KindType, code CodeType) CustomError
``` 

What do you think about it?

2021-04-26 21:46 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +func New(kind KindType, message string, code CodeType) CustomError {
Another thing: I think there is a problem with the comment of this function.

2021-04-26 21:46 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +package errors
@straubartur This package should be versioned independently. I imagine the usage of this package like the following:

`go get github.com/ditointernet/go-dito/lib/infra/errors`

Is these approach achievable? How?

2021-04-26 21:49 UTC, lcnascimento requested changes

2021-04-26 21:49 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +type CodeType string
Missing public documentation.. Same for `KindType` and `CustomError`.

2021-04-26 21:49 UTC, lcnascimento commented on lib/infra/errors/errors.go
> +	DefaultCode CodeType = ""
Should `DefaultKind` and `DefaultCode` be publicly exposed by this package?

2021-04-26 22:21 UTC, RaiTamarindo commented on lib/infra/errors/errors.go
> +type KindType string
I agree. We must define some known error kinds like:
```go
const (
    // KindInternal are errors caused by some internal fail like failed IO calls or invalid memory states
    KindInternal KindType = "INTERNAL"
    // KindInvalidInput are errors caused by some invalid values on the input
    KindInvalidInput KindType = "INVALID_INPUT"
    // KindNotFound are errors caused by any required resources that not exists on the data repository
    KindNotFound KindType = "NOT_FOUND"
    // KindAuthentication are errors caused by an unauthenticated call
    KindAuthentication KindType = "AUTHENTICATION"
    // KindAuthorization are errors caused by an unauthorized call
    KindAuthorization KindType = "AUTHORIZATION"
)
```

But I'm not shure if this package should implement the translations to the specific protocols like gRPC and REST.

2021-04-28 18:04 UTC, straubartur commented on lib/infra/errors/errors.go
> +package errors
https://github.com/go-modules-by-example/index/blob/master/009_submodules/README.md

2021-04-30 14:30 UTC, merged