package log as a lib
ditointernet/go-dito pull request #18
Opened 2021-04-30 18:58 UTC by lcnascimento

2021-05-03 19:56 UTC, RaiTamarindo requested changes

2021-05-03 19:56 UTC, RaiTamarindo commented on lib/infra/log/log.go
> +}
I got this idea to remove repeated literals from the code:
```suggestion
// Level indicates the severity of the data being logged
type Level int

const (
	// LevelDebug are debug or trace information
	LevelDebug Level = iota
	// LevelInfo are routine information
	LevelInfo
	// LevelWarning warns about events the might cause problems to the system
	LevelWarning
	// LevelError alerts about events that are likely to cause problems
	LevelError
	// LevelCritical alerts about severe problems. Most of the time, needs some human intervention ASAP
	LevelCritical
)

func (l Level) String() string {
	return []string{
		"DEBUG",
		"INFO",
		"WARNING",
		"ERROR",
		"CRITICAL",
	}[l]
}
```

2021-05-03 19:56 UTC, RaiTamarindo commented on lib/infra/log/log.go
> +	if levelPriority[l.level] >= 25 {
Thus, you can do this:
```suggestion
	if l.level >= LevelDebug {
```

2021-05-03 19:56 UTC, RaiTamarindo commented on lib/infra/log/log.go
> +	Level      Level                        `json:"level"`
```suggestion
	Level      string                        `json:"level"`
```

2021-05-03 19:56 UTC, RaiTamarindo commented on lib/infra/log/log.go
> +		Level:      level,
```suggestion
		Level:      level.String(),
```

2021-05-03 19:56 UTC, RaiTamarindo commented on lib/infra/log/log.go
> +type logData struct {
I think we can add a `timestamp` attribute to it
```suggestion
type logData struct {
	Timestamp      string                        `json:"timestamp"`
```

2021-05-05 18:38 UTC, lcnascimento commented on lib/infra/log/log.go
> +}
@RaiTamarindo nice call!!

2021-05-05 18:39 UTC, merged