inserted a http client
ditointernet/go-dito pull request #21
Opened 2021-05-17 18:27 UTC by straubartur

2021-05-18 01:56 UTC, lcnascimento requested changes

2021-05-18 01:56 UTC, lcnascimento commented on lib/http/client.go
> +	return c.processRequest(ctx, "PATCH", request)
@straubartur PATCH?

2021-05-18 01:56 UTC, lcnascimento commented on lib/http/client.go
> +	return c.processRequest(ctx, "POST", request)
@straubartur POST?

2021-05-18 13:43 UTC, lcnascimento requested changes

2021-05-18 13:43 UTC, lcnascimento commented on lib/http/value_objects.go
> +type HttpRequest struct {
@straubartur I think it should be better using `HTTPRequest`

2021-05-18 13:43 UTC, lcnascimento commented on lib/http/value_objects.go
> +type HttpResult struct {
@straubartur I think it should be better using `HTTPResult`. Also, it is missing docs.

2021-05-19 14:09 UTC, lcnascimento requested changes

2021-05-19 14:09 UTC, lcnascimento commented on lib/http/value_objects.go
> +// HTTPHeaders is a map'containing the relation key=value of the heades used on the http rest request.
@straubartur There is a typo here.

2021-05-19 14:09 UTC, lcnascimento commented on lib/http/value_objects.go
> +}
@straubartur Missing documentation

2021-05-19 15:12 UTC, lcnascimento commented on lib/http/middlewares.go
> +	ctx.SetUserValue("userID", userID)
@straubartur There is any way to extract the `brandID` from the token or it will be retrieved from the request header?

2021-05-19 17:56 UTC, straubartur commented on lib/http/middlewares.go
> +	ctx.SetUserValue("userID", userID)
@lcnascimento we need to implement a specific middleware to retrieve the brand from the headers

2021-05-19 19:52 UTC, lcnascimento approved these changes
LGTM

2021-05-19 20:08 UTC, merged