insert jwks lib
ditointernet/go-dito pull request #22
Opened 2021-05-17 20:19 UTC by straubartur

2021-05-17 22:37 UTC, straubartur commented on lib/jwks/client/contracts.go
> +type HttpRequest struct {
this params will come from http lib

2021-05-18 02:04 UTC, lcnascimento requested changes

2021-05-18 02:04 UTC, lcnascimento commented on lib/jwks/client/contracts.go
> +type HttpRequest struct {
@straubartur I think that you misunderstood how you should use contracts here. Since, you're explicitly declaring a new `HTTPRequest` at package `jwks` and using it at its `HTTPClient` contract, the go-dito's `HTTPClient` will not satisfy this contract, because it uses another `HTTPRequest`. Besides they share the same name and fields, they are different from each other. Structs do not behave like interfaces here.

2021-05-18 02:04 UTC, lcnascimento commented on lib/jwks/client/contracts.go
> +type HttpClient interface {
@straubartur As mentioned, I think the contract should use `HTTPRequest` and `HTTPResult` from go-dito's `http` package. Also, I think it should be better to declare this interface at `/lib/jwks/jwks.go`. Simplier. What do you think about it?

2021-05-18 18:44 UTC, victoriavilasb commented on lib/jwks/client/contracts.go
> +type HttpClient interface {
http should be HTTP as it is a acronym

2021-05-18 18:45 UTC, victoriavilasb commented on lib/jwks/jwks.go
> +// Client is the structure responsible for handling the JWKS certificates
```suggestion
// Client is the structure responsible for handling JWKS certificates
```

2021-05-18 19:20 UTC, straubartur commented on lib/jwks/client/contracts.go
> +type HttpClient interface {
i've tried to declere on the same level as jwks.go, but i was getting import cycle when i created the mock folder

2021-05-19 14:59 UTC, lcnascimento requested changes

2021-05-19 14:59 UTC, lcnascimento commented on lib/jwks/jwks.go
> +		c.lastRenewTime = time.Now()
@straubartur What do you think about filling this field at `fetchCerts` method?

2021-05-19 14:59 UTC, lcnascimento commented on lib/jwks/jwks.go
> +		lastRenewTime:        time.Now(),
@straubartur This constructor don't download certificates. Does it make sense to fill this field here?

2021-05-19 15:01 UTC, lcnascimento requested changes

2021-05-19 15:01 UTC, lcnascimento commented on lib/jwks/jwks.go
> +		return nil, fmt.Errorf("request was not successful. Received status: %d", resp.StatusCode)
@straubartur What do you think about using `go-dito`'s error package?

2021-05-19 15:01 UTC, lcnascimento commented on lib/jwks/jwks.go
> +	httpCLient "github.com/ditointernet/go-dito/lib/http"
@straubartur `httpClient`

2021-05-19 15:01 UTC, lcnascimento commented on lib/jwks/mocks/jwksmocks.go
> +// Code generated by MockGen. DO NOT EDIT.
@straubartur Do we need to version this file?

2021-05-19 17:56 UTC, lcnascimento approved these changes
LGTM

2021-05-19 19:49 UTC, merged