Feat/insert auth middleware
ditointernet/go-dito pull request #25
Opened 2021-05-21 13:49 UTC by straubartur

2021-05-21 19:48 UTC, straubartur commented on lib/http/middleware/authorization/authorization.go
> +	query := fmt.Sprintf(`allow := data.authz.%s_allow ; filter := data.authz.filter_values`, a.regoClient)
change regoCLient to resource name

2021-05-24 13:18 UTC, RaiTamarindo requested changes

2021-05-24 13:18 UTC, RaiTamarindo commented on lib/http/middleware/authorization/authorization.go
> +		"filter_type": "stores",
These recommendations are only to enable a future implementation with a soft transition.
Put it as a hard coded input. You can make `Authorize` function return a handler function and receive a `filterTypes` variadic parameter:
```golang
func (a AccountAuthorizator) Authorize(filterTypes ...string) func(ctx *routing.Context) error {
	return func(ctx *routing.Context) error {
```
For now use just the first (if exists) filter type, but in a near future we will enable make a query with `N` filter types.

2021-05-24 13:18 UTC, RaiTamarindo commented on lib/http/middleware/authorization/mocks/authorization.go
> +// Code generated by MockGen. DO NOT EDIT.
Please remove this file and put it into `.gitignore`

2021-05-24 14:40 UTC, lcnascimento requested changes

2021-05-24 14:40 UTC, lcnascimento commented on lib/http/middleware/authorization/authorization.go
> +	}
@straubartur What do you think about doing this validation at middleware constructor level?

2021-05-24 14:40 UTC, lcnascimento commented on lib/http/middleware/authorization/authorization.go
> +	}
Also, I think that this should be an InternalError since it should be filled by the application, not by an user input.

2021-05-24 14:40 UTC, lcnascimento commented on lib/http/middleware/authorization/authorization.go
> +		err := errors.New("missing brand id").WithKind(errors.KindInternal)
@straubartur KindInternal is the default Kind... what do you think about omiting this part of Error construction? I mean.. this makes the information more explicit and should be a good idea, but it is more verbose. What do you think about it?

2021-05-24 14:40 UTC, lcnascimento commented on lib/http/middleware/authorization/authorization.go
> +	ctx.SetUserValue(ContextKeyAllowedStores, allowedStores)
@straubartur I think that this should only be done if `StoreFilter` ResourceFilter is properly set, isn't it?

2021-05-24 14:40 UTC, lcnascimento commented on lib/http/middleware/authorization/contracts.go
> +type Logger interface {
@straubartur Missing public documentation.

2021-05-24 14:46 UTC, lcnascimento requested changes

2021-05-24 14:46 UTC, lcnascimento commented on lib/http/middleware/authorization/contracts.go
> +type Logger interface {
@straubartur It could be a private interface, isn't it?

2021-05-24 14:46 UTC, lcnascimento commented on lib/http/middleware/authorization/contracts.go
> +type AuthorizatorClient interface {
@straubartur It could be a private interface, isn't it?

2021-05-24 14:46 UTC, lcnascimento commented on lib/http/middleware/authorization/contracts.go
> +	ExecuteQuery(ctx context.Context, query string, input map[string]interface{}) (AuthQueryResult, error)
@straubartur It should use `opa.AuthorizationResult` isn't, it?

2021-05-24 19:18 UTC, lcnascimento requested changes

2021-05-24 19:18 UTC, lcnascimento commented on lib/http/middleware/authorization/authorization.go
> +	}
@straubartur Do we still need this comment?

2021-05-26 16:26 UTC, lcnascimento approved these changes

2021-05-26 16:26 UTC, merged