Feat/cdp 88
ditointernet/go-dito pull request #30
Opened 2021-06-02 23:29 UTC by lcnascimento

2021-06-07 17:39 UTC, victoriavilasb requested changes

2021-06-07 17:39 UTC, victoriavilasb commented on lib/http/middleware/brand/brand.go
>  // BrandFiller creates a new instance of the Brand structure
```suggestion
// NewBrandFiller creates a new instance of the Brand structure
```

2021-06-07 17:39 UTC, victoriavilasb commented on lib/jwks/jwks.go
> +func (c *Client) Certs() map[string]string {
Why you changed to a pointer?

2021-06-07 17:39 UTC, victoriavilasb commented on lib/trace/trace.go
> +// NewTracer creates a new Tracer.
```suggestion
// MustNewTracer creates a new Tracer.
```

2021-06-07 18:41 UTC, straubartur requested changes

2021-06-07 18:41 UTC, straubartur commented on lib/http/middleware/brand/brand.go
> +const ContextKeyBrandID string = "brand"
i think we should go fot the "brand_id" to follow the convency

2021-06-08 11:52 UTC, lcnascimento commented on lib/jwks/jwks.go
> +func (c *Client) Certs() map[string]string {
Our new linter found an issue: `RenewCerts passes lock by value: github.com/ditointernet/go-dito/lib/jwks.Client contains sync.Mutex`

2021-06-09 16:43 UTC, merged